# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jenny
subtitle: æˆ‘çš„å°ä¸¸å­ğŸ¡ï¼Œå¥¹å«Jenny.
author: Henry
language: ä¸­æ–‡
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zcoldwater.github.io/blog       # Note: don't forget to modify the CNAME file to your url
root: /blog
#permalink: :year/:month/:day/:title/
permalink: :category/:title/
permalink_defaults:
  lang: en

#Custom Setting Start

# Site settings
SEOTitle: æœ±æ°¸é¹ | Blog
email: 1486297824@qq.com
description: ""
keyword: ""
header-img: https://upload-images.jianshu.io/upload_images/1793544-20594f91db13f6ba.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240
article-img: https://upload-images.jianshu.io/upload_images/1793544-20594f91db13f6ba.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240
404-img: https://upload-images.jianshu.io/upload_images/1793544-47b919dc9696fb2b.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240
signature: true #show signature
signature-img: https://upload-images.jianshu.io/upload_images/1793544-47b919dc9696fb2b.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240 


# SNS settings
# RSS: false
# weibo_username:     Demonbaneen
# zhihu_username:     Demonbane
github_username:    zColdWater
# twitter_username:   Demonbane_x
# facebook_username:  YenYuHsuan
# linkedin_username:  yongpeng.zhu

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
#disqus_username: your-disqus-ID

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: r45fhy7653897235wg5ye709d930f62e
# Google Analytics
ga_track_id: 'UA-XXXXXXXX-X'          # Format: UA-xxxxxx-xx
ga_domain: yoursite


# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "æ°¸è¿œéƒ½æ€€ç€ä¸€é¢—å­¦å¾’çš„å¿ƒ"
sidebar-avatar: https://upload-images.jianshu.io/upload_images/1793544-f9689d2f20140b0b.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
#- category

# widget behavior
## Archive
archives-img: https://upload-images.jianshu.io/upload_images/1793544-20594f91db13f6ba.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


## Friends
friends: [
    {
        title: "ç®€ä¹¦ ä¸€äººæˆ‘ç¼–ç¨‹ç´¯",
        href: "https://www.jianshu.com/u/fd1a9ea4a20e"
    },
    {
        title: "æ˜é‡‘ ä¸€äººæˆ‘ç¼–ç¨‹ç´¯",
        href: "https://juejin.im/user/59435c5da0bb9f006b913d54"
    }
]

#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: article
category_map:
  Docker: docker
  Kubernetes: kubernetes
  Golang: golang
  Nginx: nginx
  Etcd: etcd
  Database: database

tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: 'â€œâ€â€˜â€™'
  
# Extensions
## Plugins: https://hexo.io/plugins/

# recommended-posts
# reference: https://github.com/huiwang/hexo-recommended-posts
# recommended_posts:
#   server: https://api.truelaurel.com #åç«¯æ¨èæœåŠ¡å™¨åœ°å€
#   timeoutInMillis: 10000 #æœåŠ¡æ—¶é•¿ï¼Œè¶…è¿‡æ­¤æ—¶é•¿ï¼Œåˆ™ä½¿ç”¨ç¦»çº¿æ¨èæ¨¡å¼
#   internalLinks: 3 #å†…éƒ¨æ–‡ç« æ•°é‡
#   externalLinks: 0 #å¤–éƒ¨æ–‡ç« æ•°é‡
#   autoDisplay: true, #è‡ªåŠ¨åœ¨æ–‡ç« åº•éƒ¨æ˜¾ç¤ºæ¨èæ–‡ç« 
#   titleHtml: <h2>æ¨èæ–‡ç« <span style="font-size:0.45em; color:gray"></span></h2> #è‡ªå®šä¹‰æ ‡é¢˜

# hexo-tag-aplayer
# reference: https://github.com/MoePlayer/hexo-tag-aplayer
# aplayer:
#   meting: true

# MeingJS support for Aplayer
# reference: https://github.com/metowolf/MetingJS & https://github.com/MoePlayer/APlayer
metingjs: false
data-id: 2423410161
data-server: netease  
data-type: playlist
data-fixed: true
  # data-mini:
  # data-autoplay:    

## Themes: https://hexo.io/themes/
theme: huweihuang

#sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# repository: https://github.com/huweihuang/xxxxxxx.github.io.git
# branch: master
deploy:
  type: git
  repo: git@github.com:zColdWater/blog.git
  branch: master
