# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jenny
subtitle: Stay hungry, Stay foolish. 123
author: Henry
language: 中文
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zcoldwater.github.io/blog       # Note: don't forget to modify the CNAME file to your url
root: /blog
#permalink: :year/:month/:day/:title/
permalink: :category/:title/
permalink_defaults:
  lang: en

#Custom Setting Start

# Site settings
SEOTitle: 朱永鹏 | Blog
email: 1486297824@qq.com
description: ""
keyword: ""
header-img: https://raw.githubusercontent.com/zColdWater/Resources/master/Images/cover.jpg
article-img: https://raw.githubusercontent.com/zColdWater/Resources/master/Images/cover.jpg
404-img: https://raw.githubusercontent.com/zColdWater/Resources/master/Images/cover.jpg
signature: true #show signature
signature-img: https://raw.githubusercontent.com/zColdWater/Resources/master/Images/cover.jpg 


# SNS settings
# RSS: false
# weibo_username:     Demonbaneen
# zhihu_username:     Demonbane
github_username:    zColdWater
jianshu_userid:     fd1a9ea4a20e
juejin_userid:      59435c5da0bb9f006b913d54
# twitter_username:   Demonbane_x
# facebook_username:  YenYuHsuan
# linkedin_username:  yongpeng.zhu

# 微信加好友 二维码图片地址
wx_personal_qrcode: https://raw.githubusercontent.com/zColdWater/Resources/master/Images/addMe.jpeg

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
#disqus_username: your-disqus-ID

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# 腾讯MTA H5 统计方案
# H5 App id: 500655555
# H5 App Secret key: 96582d45fedd2828ff02579c50b08d33
mta_sid: 500655555

# 评论系统 settings
# 来必力
livere_uid: TAyMC80MDg5Ni8xNzQyMQ==




# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "侠客行 \n赵客缦胡缨，吴钩霜雪明。\n银鞍照白马，飒沓如流星。\n十步杀一人，千里不留行。\n事了拂衣去，深藏身与名。"
sidebar-avatar: https://raw.githubusercontent.com/zColdWater/Resources/master/Images/me.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
#- category

# widget behavior
## Archive
archives-img: https://raw.githubusercontent.com/zColdWater/Resources/master/Images/cover.jpg
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


## Friends
# friends: [
#     {
#         title: "简书 一人我编程累",
#         href: "https://www.jianshu.com/u/fd1a9ea4a20e"
#     },
#     {
#         title: "掘金 一人我编程累",
#         href: "https://juejin.im/user/59435c5da0bb9f006b913d54"
#     }
# ]

#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: article
category_map:
  Docker: docker
  Kubernetes: kubernetes
  Golang: golang
  Nginx: nginx
  Etcd: etcd
  Database: database

tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  
# Extensions
## Plugins: https://hexo.io/plugins/

# recommended-posts
# reference: https://github.com/huiwang/hexo-recommended-posts
# recommended_posts:
#   server: https://api.truelaurel.com #后端推荐服务器地址
#   timeoutInMillis: 10000 #服务时长，超过此时长，则使用离线推荐模式
#   internalLinks: 3 #内部文章数量
#   externalLinks: 0 #外部文章数量
#   autoDisplay: true, #自动在文章底部显示推荐文章
#   titleHtml: <h2>推荐文章<span style="font-size:0.45em; color:gray"></span></h2> #自定义标题

# hexo-tag-aplayer
# reference: https://github.com/MoePlayer/hexo-tag-aplayer
# aplayer:
#   meting: true

# MeingJS support for Aplayer
# reference: https://github.com/metowolf/MetingJS & https://github.com/MoePlayer/APlayer

metingjs: false
data-id: 2423410161
data-server: netease  
data-type: playlist
data-fixed: true
  # data-mini:
  # data-autoplay:    

## Themes: https://hexo.io/themes/
theme: huweihuang

#sitemap
sitemap:
  path: sitemap.xml


# Deployment
## Docs: https://hexo.io/docs/deployment.html
# repository: https://github.com/huweihuang/xxxxxxx.github.io.git
# branch: master

deploy:
  type: git
  repo: https://zColdWater:gh_password@github.com/zColdWater/blog.git
  branch: master
